import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#47464a",
        "background": "#131315",
        "outline": "#958ea0",
        "primary-fixed": "#e9ddff",
        "primary": "#d0bcff",
        "on-tertiary-fixed": "#1b1b1e",
        "outline-variant": "#494454",
        "on-primary-container": "#340080",
        "primary-fixed-dim": "#d0bcff",
        "on-tertiary-container": "#29292c",
        "on-background": "#e5e1e4",
        "surface-variant": "#353437",
        "on-primary-fixed-variant": "#5516be",
        "surface-container": "#201f22",
        "tertiary-fixed": "#e4e1e5",
        "secondary-fixed": "#e4e1e6",
        "surface-tint": "#d0bcff",
        "inverse-primary": "#6d3bd7",
        "primary-container": "#a078ff",
        "surface-bright": "#39393b",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1c1b1d",
        "on-primary": "#3c0091",
        "on-tertiary": "#303033",
        "surface-dim": "#131315",
        "on-surface-variant": "#cbc3d7",
        "on-tertiary-fixed-variant": "#47464a",
        "secondary-container": "#47464a",
        "on-secondary-fixed": "#1b1b1e",
        "surface-container-lowest": "#0e0e10",
        "surface-container-highest": "#353437",
        "error": "#ffb4ab",
        "inverse-on-surface": "#313032",
        "tertiary-container": "#919094",
        "on-secondary": "#303033",
        "inverse-surface": "#e5e1e4",
        "on-primary-fixed": "#23005c",
        "surface": "#131315",
        "error-container": "#93000a",
        "tertiary": "#c8c6c9",
        "on-secondary-container": "#b6b4b8",
        "secondary": "#c8c5ca",
        "on-surface": "#e5e1e4",
        "surface-container-high": "#2a2a2c",
        "tertiary-fixed-dim": "#c8c6c9",
        "secondary-fixed-dim": "#c8c5ca",
        // Legacy palette kept for emerald badge on upload page
        indigo: { DEFAULT: '#6366f1', light: '#818cf8', dark: '#4f46e5' },
        violet: { DEFAULT: '#8b5cf6' },
        emerald: {
          400: '#34d399',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      animation: {
        'spin-slow': 'spin 2s linear infinite',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
  darkMode: 'class',
};

export default config;
